/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/components/ButtonPage': RouteRecordInfo<'/components/ButtonPage', '/components/button', Record<never, never>, Record<never, never>>,
    '/components/FontPage': RouteRecordInfo<'/components/FontPage', '/components/font', Record<never, never>, Record<never, never>>,
    '/components/LoadingPage': RouteRecordInfo<'/components/LoadingPage', '/components/loading', Record<never, never>, Record<never, never>>,
    '/components/ModalPage': RouteRecordInfo<'/components/ModalPage', '/components/modal', Record<never, never>, Record<never, never>>,
    '/FunctionrPage': RouteRecordInfo<'/FunctionrPage', '/function', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/home', Record<never, never>, Record<never, never>>,
    '/LayoutPage': RouteRecordInfo<'/LayoutPage', '/layout', Record<never, never>, Record<never, never>>,
    '/modules/ConfigurationPage': RouteRecordInfo<'/modules/ConfigurationPage', '/modules/fbl-ovp-configuration', Record<never, never>, Record<never, never>>,
    '/modules/NetworkHttpPage': RouteRecordInfo<'/modules/NetworkHttpPage', '/modules/fbl-ovp-network-http', Record<never, never>, Record<never, never>>,
    '/modules/StorePage': RouteRecordInfo<'/modules/StorePage', '/modules/fbl-ovp-store', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/not-found', Record<never, never>, Record<never, never>>,
    '/RouterPage': RouteRecordInfo<'/RouterPage', '/router', Record<never, never>, Record<never, never>>,
    '/StylePage': RouteRecordInfo<'/StylePage', '/style', Record<never, never>, Record<never, never>>,
  }
}
