services:
  bamboo:    
    container_name: bamboo
    build:
      context: .
      dockerfile: Dockerfile.bamboo
    ports:
      - "8085:8085"
    volumes:
      - C:/Bamboo/data:/var/atlassian/application-data/bamboo
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge